# Automatically generated by pb2py
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class BIP32Derivation(p.MessageType):
    FIELDS = {
        1: ('master_pubkey', p.BytesType, 0),
        2: ('path', p.Fixed32Type, p.FLAG_REPEATED),
    }

    def __init__(
        self,
        master_pubkey: bytes = None,
        path: List[int] = None
    ) -> None:
        self.master_pubkey = master_pubkey
        self.path = path if path is not None else []
