# Automatically generated by pb2py
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None
from .BIP32Derivation import BIP32Derivation
from .PartialSignature import PartialSignature


class InputType(p.MessageType):
    FIELDS = {
        1: ('non_witness_utxo', p.BytesType, 0),
        2: ('witness_utxo', p.BytesType, 0),
        3: ('partial_signature', PartialSignature, 0),
        4: ('sighash_type', p.UVarintType, 0),
        5: ('redeem_script', p.BytesType, 0),
        6: ('witness_script', p.BytesType, 0),
        7: ('bip32_path', BIP32Derivation, p.FLAG_REPEATED),
        8: ('finalized_scriptsig', p.BytesType, 0),
        9: ('finalized_scriptwitness', p.BytesType, 0),
    }

    def __init__(
        self,
        non_witness_utxo: bytes = None,
        witness_utxo: bytes = None,
        partial_signature: PartialSignature = None,
        sighash_type: int = None,
        redeem_script: bytes = None,
        witness_script: bytes = None,
        bip32_path: List[BIP32Derivation] = None,
        finalized_scriptsig: bytes = None,
        finalized_scriptwitness: bytes = None
    ) -> None:
        self.non_witness_utxo = non_witness_utxo
        self.witness_utxo = witness_utxo
        self.partial_signature = partial_signature
        self.sighash_type = sighash_type
        self.redeem_script = redeem_script
        self.witness_script = witness_script
        self.bip32_path = bip32_path if bip32_path is not None else []
        self.finalized_scriptsig = finalized_scriptsig
        self.finalized_scriptwitness = finalized_scriptwitness
