# Automatically generated by pb2py
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None
from .BIP32Derivation import BIP32Derivation


class OutputType(p.MessageType):
    FIELDS = {
        1: ('redeem_script', p.BytesType, 0),
        2: ('witness_script', p.BytesType, 0),
        3: ('bip32_path', BIP32Derivation, p.FLAG_REPEATED),
    }

    def __init__(
        self,
        redeem_script: bytes = None,
        witness_script: bytes = None,
        bip32_path: List[BIP32Derivation] = None
    ) -> None:
        self.redeem_script = redeem_script
        self.witness_script = witness_script
        self.bip32_path = bip32_path if bip32_path is not None else []
